### ISSUE TITLE
Adding await before fireEvent seems to work ok

### ISSUE THREAD

**Issue by gusaiani** [kentcdodds/dom-testing-library-with-anything#16]
Hi @kentcdodds, 

working on https://testingjavascript.com/lessons/javascript-use-dom-testing-library-with-preact

At the point where you use the custom fireEventAsync, I somewhat randomly left it as `await fireEvent`, and it worked.

~~~js
test('renders a counter', async () => {
  const {getByText} = render(<Counter />)
  const counter = getByText('0')

  // This works
  await fireEvent.click(counter)
  expect(counter).toHaveTextContent('1')

  // This still does not work
  fireEvent.click(counter)
  expect(counter).toHaveTextContent('2')
})
~~~

As you created `fireEvent`, it may be a recent change to it, who knows, just thought to mention it.

Cheers!

**Comment by gusaiani** [comment]
This also works

~~~js
  fireEvent.click(counter)
  await expect(counter).toHaveTextContent('1')
~~~

I suppose await itself waits for the next tick ¯\_(ツ)_/¯

**Comment by kentcdodds** [comment]
Hi @gusaiani,

Thanks for mentioning this. Actually, it just happens to work, but it's not officially supported so I don't think we should document it :)

Thanks anyway!
