### ISSUE TITLE
Svelte tests are stalling indefinitely

### ISSUE THREAD

**Issue by nickserv** [kentcdodds/dom-testing-library-with-anything#17]
Running `npm test` just displays `RUN` next to `svelte.test.js`, even if I wait more than a minute. I thought I saw some sort of error about transforms before, but I can't reproduce it any more.

**Comment by kentcdodds** [comment]
I'm going to be updating this for an update to TestingJavaScript after EpicReact is launched. I'll take a look at this at that time.

**Comment by nickserv** [comment]
Strange, it [works on Travis](https://travis-ci.com/github/kentcdodds/dom-testing-library-with-anything/builds/181691979#L271). Maybe it's just me.

**Comment by ashsearle** [comment]
@nickmccurdy It's not just you.  I saw this too.  Updating `svelte` and `jest-transform-svelte` got things working again for me.

**Comment by kentcdodds** [comment]
This repo has also been completely updated as of yesterday 😁
