### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by sibelius** [kentcdodds/dom-testing-library-with-anything#23]
https://testingjavascript.com/courses/use-dom-testing-library-to-test-any-js-framework

![image](https://user-images.githubusercontent.com/2005841/113332951-3f829800-92f8-11eb-9c92-9f444ba32dfe.png)

**Comment by dealingwith** [comment]
@sibelius the most up-to-date link for that course is https://testingjavascript.com/playlists/use-dom-testing-library-to-test-any-js-framework-ae28 which is what is linked to from the course home page. How did you arrive at the above URL? Likely the original link needs to be updated.

**Comment by sibelius** [comment]
![image](https://user-images.githubusercontent.com/2005841/113343749-9a22f080-9306-11eb-820a-019ebd27ab6c.png)

the link on about

**Comment by dealingwith** [comment]
Ah, thank you! :)

**Comment by kentcdodds** [comment]
Fixed. Thanks!
